### ISSUE TITLE
Possibility to select text on pages

### ISSUE THREAD

**Issue by klimeto** [HRSEVESOSK/cide-ionic-app#3]
User shall have an option to select any text displayed on pages. Now it does not allow to do it.

**Comment by klimeto** [comment]
Added:
```css
body{
  user-select: text;
  -webkit-user-select: text;
}
```
to app.scss.

Now text selection is enabled.
